FROM debian:stretch-slim

LABEL maintainer="calvintam236"
LABEL description="XMRig in Docker. Supports CPU mining."

WORKDIR /tmp/

ADD \
https://github.com/xmrig/xmrig/releases/download/v2.14.4/xmrig-2.14.4-xenial-x64.tar.gz \
.

RUN \
tar -xvf xmrig-2.14.4-xenial-x64.tar.gz \
&& mv xmrig-2.14.4/xmrig /usr/local/bin/xmrig \
&& chmod +x /usr/local/bin/xmrig \
&& rm -r *

ENTRYPOINT ["xmrig"]
CMD ["-h"]
